src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="dtype", type="string")
 * @ORM\DiscriminatorMap({"reservation" = "Reservation",
"reservationTatoo" = "ReservationTatoo","reservationpiercing" = "ReservationPiercing","reservationmicro" = "ReservationMicro"})
 *
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $DateReservation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Etat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $UnUtilisateur;

	/**
	 * Reservation constructor.
	 * @param $DateReservation
	 * @param $Etat
	 * @param $message
	 * @param $UnUtilisateur
	 */
	public function __construct($DateReservation, $Etat, $message, $UnUtilisateur)
	{
		$this->DateReservation = $DateReservation;
		$this->Etat = $Etat;
		$this->message = $message;
		$this->UnUtilisateur = $UnUtilisateur;
	}


	public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReservation()
    {
        return $this->DateReservation;
    }

    public function setDateReservation($DateReservation): self
    {
        $this->DateReservation = $DateReservation;

        return $this;
    }

    public function getEtat()
    {
        return $this->Etat;
    }

    public function setEtat($Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getUnUtilisateur()
    {
        return $this->UnUtilisateur;
    }

    public function setUnUtilisateur( $UnUtilisateur): self
    {
        $this->UnUtilisateur = $UnUtilisateur;

        return $this;
    }

	public function __toString()
	{
		return strval($this->id);
	}
}

src/Entity/ReservationMicro.php
<?php

namespace App\Entity;

use App\Repository\ReservationMicroRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="ReservationMicro")
 * @ORM\Entity(repositoryClass=ReservationMicroRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 */
class ReservationMicro extends Reservation
{

	/**
	 * @return mixed
	 */
	public function getPartieCorps()
	{
		return "null";
	}

	/**
	 * @return mixed
	 */
	public function getAllergie()
	{
		return 'null';
	}

	/**
	 * @return mixed
	 */
	public function getTaille()
	{
		return "null";
	}

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('message', TextareaType::class)
	        ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\ReservationPiercing;
use App\Entity\ReservationMicro;
use App\Entity\ReservationTatoo;
use App\Form\PiercingType;
use App\Form\ReservationType;
use App\Form\TatouageType;
use App\Form\MicroType;
use App\Notification\MailNotification;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Notifier\Recipient\Recipient;

class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation", name="reservation")
     */
    public function index(): Response
    {
    	/*Current Week(1)*/
    	$dateStart = $this->getWeekdayStart("last monday");
	    $dateEnd = $this->getWeekdayEnd("last monday");
	    $Jours = [];
	    $jourST=intval($dateStart[2])+1;
	    $i=$jourST;
	    $jourED=intval($dateEnd[2]);
	    $CuurentDay = $this->getCuurentDay();
	    while($i <= $jourED-1){
	        $Jours[] = $jourST++;
	        $i++;
	    }
	    /*Next Week(2)*/
	    $dateNStart = $this->getWeekdayStart("next monday");
	    $dateNEnd = $this->getWeekdayEnd("next monday");
	    $JoursN = [];
	    $jourSTN=intval($dateNStart[2])+1;
	    $iN=$jourSTN;
	    $jourEDN=intval($dateNEnd[2]);
	    while($iN <= $jourEDN-1){
		    $JoursN[] = $jourSTN++;
		    $iN++;
	    }
	    /*Another Week(3)*/
	    $dateAStart = $this->getWeekdayStart("next monday +1 week");
	    $dateAEnd = $this->getWeekdayEnd("next monday +1 week");
	    $JoursA = [];
	    $jourSTA=intval($dateAStart[2])+1;
	    $iA=$jourSTA;
	    $jourEDA=intval($dateAEnd[2]);
	    while($iA <= $jourEDA-1){
		    $JoursA[] = [
		    	"Jours"=>$jourSTA++
		    ];
		    $iA++;
	    }

	    /*the reservation*/
	    $em = $this->getDoctrine()->getManager();
	    $reservations = $em->getRepository(Reservation::class)->findAll();
	    $userReservations = [];
	    $user = $this->get('security.token_storage')->getToken()->getUser();
	    $reservationd ='';

	    foreach ($reservations as $res){
	    	if ($res->getUnUtilisateur() == $user){
			    $userReservations [] = $res;
			    $reservationd = $em->getRepository(Reservation::class)->findIdUser($res->getUnUtilisateur());
			    $reservationd = $reservationd[0]['id'];
		    }
	    }

        return $this->render('reservation/index.html.twig', [
            'controller_name' => 'ReservationController',
	        "date"=>$Jours,
	        "Nextdate"=>$JoursN,
	        'Another'=>$JoursA,
	        "Current"=>$CuurentDay,
	        "reservations"=>$userReservations,
	        "resId"=>$reservationd

        ]);
    }

	/**
	 * @Route("/reservation/{jour}", name="days")
	 */
	public function reservation($jour): Response
	{
		$heures=[
			"10","11","12","14","15","16","17","18","19"
		];
		$CuurentHour = $this->getCuurentHour();
		$t = $this->getDateDay("last monday",$jour);
		$dateCheck = date("d", strtotime("now"));
		return $this->render('reservation/choices.html.twig', [
			'controller_name' => 'ReservationController',
			"t"=>$t,
			"heures"=>$heures,
			"HeureEnCours"=>$CuurentHour,
			"dateCheck"=>$dateCheck,
			"j"=>$jour
		]);
	}

	/**
	 * @Route("/reservation/validation/{date}/{heure}/{type}", name="validation")
	 */
	public function validation($date,$heure,$type, Request $request,MailNotification $mail): Response
	{
		$Date= $date;
		$Heure=$heure;
		$dateForDb = new\DateTime($Date);
		$dateForDb->setTime(intval($Heure),00);
		$jour = explode('-',$date);
		$user = $this->get('security.token_storage')->getToken()->getUser();
		$er='';


		if ($type == "tatouage" || $type == "piercing" || $type == "microblading") {
			if ($type == "tatouage") {
				$reservation = new ReservationTatoo($dateForDb, "attente", "", $user);
				$form = $this->createForm(TatouageType::class, $reservation);
				$form->handleRequest($request);
				if ($form->isSubmitted() && $form->isValid()) {
					$reservation = $form->getData();
					$reservation->setDateReservation($dateForDb);
					$reservation->setEtat("attente");
					$reservation->setMessage($form->get("message")->getData());
					$reservation->setUnUtilisateur($user);

					if ($dateForDb->format('H') >= 10 and $dateForDb->format('H') <= 19) {
						$entityManager = $this->getDoctrine()->getManager();
						$entityManager->persist($reservation);
						$entityManager->flush();
						$mail->notify("Rendez-vous pour un Tatouage",'laury.p@hotmail.fr',$reservation->getDateReservation(),$reservation->getMessage(), "Vous avez reçu une demande de rendez-vous !");

						return $this->redirectToRoute('reservation');
					} else {
						$er = 'Vous pouvez prendre rendez-vous uniquement entre 10h et 19h';
					}
				}
			}

			if ($type == "microblading") {
				$reservation = new ReservationMicro($dateForDb, "attente", "", $user);
				$form = $this->createForm(MicroType::class, $reservation);
				$form->handleRequest($request);
				if ($form->isSubmitted() && $form->isValid()) {
					$reservation = $form->getData();
					$reservation->setDateReservation($dateForDb);
					$reservation->setEtat("attente");
					$reservation->setMessage($form->get("message")->getData());
					$reservation->setUnUtilisateur($user);

					if ($dateForDb->format('H') >= 10 and $dateForDb->format('H') <= 19) {
						$entityManager = $this->getDoctrine()->getManager();
						$entityManager->persist($reservation);
						$entityManager->flush();
						$mail->notify("Rendez-vous pour un Microblading",'laury.p@hotmail.fr',$reservation->getDateReservation(),$reservation->getMessage(), "Vous avez reçu une demande de rendez-vous !");
						return $this->redirectToRoute('reservation');
					} else {
						$er = 'Vous pouvez prendre rendez-vous uniquement entre 10h et 19h';
					}
				}
			}

			if ($type == "piercing") {
				$reservation = new ReservationPiercing($dateForDb, "attente", "", $user);
				$form = $this->createForm(PiercingType::class, $reservation);
				$form->handleRequest($request);
				if ($form->isSubmitted() && $form->isValid()) {
					$reservation = $form->getData();
					$reservation->setDateReservation($dateForDb);
					$reservation->setEtat("attente");
					$reservation->setMessage($form->get("message")->getData());
					$reservation->setUnUtilisateur($user);

					if ($dateForDb->format('H') >= 10 and $dateForDb->format('H') <= 19) {
						$entityManager = $this->getDoctrine()->getManager();
						$entityManager->persist($reservation);
						$entityManager->flush();
						$mail->notify("Rendez-vous pour un piercing",'laury.p@hotmail.fr',$reservation->getDateReservation(),$reservation->getMessage(), "Vous avez reçu une demande de rendez-vous !");
						return $this->redirectToRoute('reservation');
					} else {
						$er = 'Vous pouvez prendre rendez-vous uniquement entre 10h et 19h';
					}
				}
			}
		}else{
			return $this->redirectToRoute('reservation',[""]);
		}



		return $this->render('reservation/validation.html.twig', [
			'controller_name' => 'ReservationController',
			"date"=>$Date,
			"heure"=>$Heure,
			"jour"=>$jour[2],
			'form' => $form->createView(),
			'erreur'=>$er,
			"type"=>$type
		]);
	}

	/**
	 * @Route("/reservation/annuler/{id}", name="annuler")
	 * @param $id
	 * @param MailNotification $mail
	 * @return Response
	 */
	public function annuler($id, MailNotification $mail)
	{
		$entityManager = $this->getDoctrine()->getManager();
		$reservation = $entityManager->getRepository(Reservation::class)->find($id);
		$date= $reservation->getDateReservation();
		$mail->notify("Annulation de rendez-vous",$reservation->getUnUtilisateur()->getMail(),$reservation->getDateReservation(),$reservation->getMessage(), "Vous avez annulez votre rendez-vous du :");
		$mail->notify("Annulation de rendez-vous",'laury.p@hotmail.fr',$reservation->getDateReservation(),$reservation->getMessage(), "Le client à annuler le rendez-vous du :");

		$entityManager->remove($reservation);
		$entityManager->flush();

		return $this->redirectToRoute('reservation');
	}

	/**
	 * @return false|string[]
	 * Retourne début la semaine courante
	 */
	public function getWeekdayStart(String $string) {

		$monday = strtotime($string);

		$monday = date('w', $monday)==date('w') ? $monday+7*86400 : $monday;

		$sunday = strtotime(date("Y-m-d",$monday)." +6 days");

		$this_week_sd = date("Y-m-d",$monday);

		$jour = explode('-',$this_week_sd);


		return  $jour;

	}

	/**
	 * @return false|string[]
	 * Retourne fin la semaine courante
	 */
	public function getWeekdayEnd($string) {

		$monday = strtotime($string);

		$monday = date('w', $monday)==date('w') ? $monday+7*86400 : $monday;

		$sunday = strtotime(date("Y-m-d",$monday)." +6 days");

		$this_week_ed = date("Y-m-d",$sunday);

		$jour = explode('-',$this_week_ed);


		return  $jour;

	}

	/**
	 * @return false|string[]
	 * Retourne début la semaine courante
	 */
	public function getDateDay(String $string,String $day) {

		$monday = strtotime($string);

		$monday = date('w', $monday)==date('w') ? $monday+7*86400 : $monday;

		$sunday = strtotime(date("Y-m-".$day,$monday)." +6 days");

		$this_week_sd = date("Y-m-".$day,$monday);

		return  $this_week_sd;

	}

	/**
	 * @return int
	 */
	public function getCuurentDay() {

		$monday = date( "Y-m-d", strtotime( "now" ));
		$jour = explode('-',$monday);

		return  intval($jour[2]);

	}

	/**
	 * @return int
	 */
	public function getCuurentHour() {

		$monday = date( "H", strtotime( "now" ));

		return  $monday;

	}




}

templates/reservation/choices.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
<style>
</style>

    <!-- Profil -->
    <section>
        <div class="-mt-4">
            {% include('profil.html.twig') %}
                <div class="flex-1 flex flex-col overflow-hidden">
                    <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-nav-light">
                        <div class="flex items-center">
                            <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
                                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round"></path>
                                </svg>
                            </button>
                        </div>
                    </header>
                    <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                        <div class="container mx-auto px-6 py-8">
                            <h3 class="text-gray-700 text-3xl font-medium">Profil</h3>

                            <div class="mt-4 bg-white rounded">
                                <div class="container mx-auto text-center">
                                    <article class="py-12 px-4 ml-4">
                                        <h1 class="text-4xl text-center mb-4 font-semibold font-heading font-semibold">Choix de l'heure du rendez-vous .</h1>

                                        <div class="max-w-3xl mx-auto">
                                            <p class="mb-4">Vous pouvez choisir une heure de rendez-vous .  </p>
                                           <hr>
                                            <div class="container">
                                                    <div class="flex justify-center p-4 mb-10">
                                                        <h1 class="text-xl text-blue-500">Heure de rendez-vous.</h1>
                                                    </div>
                                                    <div class="flex justify-center">
                                                        <div class="bg-nav-light sm:w-11/12  lg:w-2/4 shadow-xl rounded-lg">
                                                            <p class="text-lg text-blue-500">Disponible = vert / Indisponible = gris</p>
                                                            <ul class="divide-y divide-gray-300">
                                                                {% for heure in heures %}
                                                                    {% if HeureEnCours+1 >= heure and dateCheck == j %}
                                                                            <li class="p-4 bg-gray-400 cursor-pointer">
                                                                                <p class="text-textC">{{ heure }}H</p>
                                                                            </li>
                                                                        {% else %}
                                                                            <li class="p-4 flex flex-col bg-nav-light cursor-pointer">
                                                                                <p class="text-textC">{{ heure }}H</p>
                                                                                <a class="mt-3 m-2 w-4/12 mx-auto bg-nav-dark hover:bg-btnBack hover:text-white px-1 py-1 rounded"
                                                                                   href="{{ path('validation', {"date": t, "heure": heure,"type": "tatouage" }) }}">Rdv tatouage</a>
                                                                                <a class="m-3 bg-nav-dark w-4/12 mx-auto hover:bg-btnBack hover:text-white px-2 py-1 rounded"
                                                                                   href="{{ path('validation', {"date": t, "heure": heure,"type": "piercing" }) }}">Rdv piercing</a>
                                                                                <a class="m-3 bg-nav-dark w-4/12 mx-auto hover:bg-btnBack hover:text-white px-2 py-1 rounded"
                                                                                   href="{{ path('validation', {"date": t, "heure": heure,"type": "microblading" }) }}">Rdv Microblading</a>
                                                                            </li>
                                                                    {% endif %}
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    </div>
                                            </div>
                                        </div>
                                        <div class="mt-5">
                                            <a class="rounded px-2 py-1 bg-nav-light hover:bg-btnBack hover:text-white" href="{{ path("reservation") }}">Revenir au choix du jour.</a>
                                        </div>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        </div>
    </section>
    {% else %}
        <p class="text-3xl m-96">Veuillez vous reconnecter ! <a class="bg-nav-dark px-2 py-1 rounded hover:text-white hover:bg-btnBack" href="{{ path("app_login") }}">Se connecter !</a></p>
    {% endif %}
{% endblock %}

templates/reservation/validation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <style>
    </style>

    <!-- Profil -->
    <section>
        <div class="-mt-4">
            {% include('profil.html.twig') %}
            <div class="flex-1 flex flex-col overflow-hidden">
                <header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-nav-light">
                    <div class="flex items-center">
                        <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"></path>
                            </svg>
                        </button>
                    </div>
                </header>
                <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                    <div class="container mx-auto px-6 py-8">
                        <h3 class="text-gray-700 text-3xl font-medium">Validation rendez-vous</h3>

                        <div class="mt-4 bg-white rounded">
                            <div class="container mx-auto text-center">
                                <article class="py-12 px-4 ml-4">
                                    <h1 class="text-4xl text-center mb-4 font-semibold font-heading font-semibold">Rendez-vous pour un {{ type }} .</h1>

                                    <div class="max-w-3xl mx-auto">
                                        <p class="mb-4">Il vous faut maintenant valider votre choix pour créer une demande de rendez-vous. </p>
                                        <p class="mb-4 text-rouge">Une fois votre rendez-vous pris, il faut encore qu'il soit validé par le responsable du site, vous pourrez voir
                                            l'état de
                                            votre rendez-vous dans "Mes rendez-vous" qui se trouve dans votre profil !</p>
                                        <hr>
                                        <div class="mt-5">
                                            {% if app.user.Majeur == false %}
                                                <p class="mb-4 text-lg text-rouge">Tu n'es pas majeur il te faudra une autorisation parentale,
                                                Tu devra venir accompagner avec un parent !</p>
                                            {% else %}
                                                <p class="mb-4 text-lg text-vert">Tu est majeur, il ne te reste qu'a remplir le formulaire !</p>
                                            {% endif %}
                                            {% if form is not empty %}
                                                {{ form_start(form) }}
                                                <p>Vous avez choisi de prendre rendez-vous le {{ date }} à {{ heure }}.</p>
                                                {% if form.partieCorps is defined and  form.allergie is defined %}
                                                    {{ form_widget(form.partieCorps, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2
                                                     px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline',
                                                        "placeholder": "Indique la partie du corps."}}) }}

                                                    {% if form.taille is defined %}
                                                    {{ form_widget(form.taille,
                                                        {'attr': {'class': 'shadow appearance-none border rounded w-full py-2
                                                     px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline',
                                                            "placeholder": "Indique la taille du tatouage."}}) }}
                                                        {% endif %}

                                                    {{ form_widget(form.allergie,
                                                        {'attr': {'class': 'shadow appearance-none border rounded w-full py-2
                                                     px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline',
                                                            "placeholder": "Indique pourquoi vous souhaitez prendre rendez-vous."}}) }}
                                                {% endif %}
                                                {{ form_widget(form.message,
                                                    {'attr': {'class': 'shadow appearance-none border rounded w-full py-2
                                                     px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline',
                                                        "placeholder": "Indiqué pourquoi vous souhaitez prendre rendez-vous."}}) }}
                                                {{ form_widget(form.submit,{
                                                    "label": "Envoyer",
                                                     'attr': {'class': 'shadow appearance-none border rounded w-full py-2
                                                     px-3 text-gray-700 bg-nav-dark hover:bg-btnBack hover:text-white mt-1 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                                                {{ form_end(form) }}
                                                {% if erreur %}
                                                    {{ erreur }}
                                                {% endif %}
                                            {% else %}
                                            <p>Pas de réservation pour le moment !</p>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="mt-5">
                                        <a class="rounded px-2 py-1 bg-nav-light hover:bg-btnBack hover:text-white" href="{{ path("days", {'jour': jour})
                                        }}">Revenir au choix
                                            de l'heure.</a>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        </div>
    </section>
    {% else %}
        <p class="text-3xl m-96">Veuillez vous reconnecter ! <a class="bg-nav-dark px-2 py-1 rounded hover:text-white hover:bg-btnBack" href="{{ path("app_login") }}">Se connecter !</a></p>
    {% endif %}
{% endblock %}